shap_calculator:
  # SHAP calculation settings
  shap_settings:
    val_data_path: "/cmnfs/home/j.lapin/projects/shabaz/data/shap_input.parquet"
    output_dir: ETciD
    mode:
      - a5
      - a9
      - a5^2
      - a9^2
      - A5
      - A9
      - A5^2
      - A9^2
      - b5
      - b9
      - b5^2
      - b9^2
      - c5
      - c9
      - c5^2
      - c9^2
      - C5
      - C9
      - C5^2
      - C9^2
      - y5
      - y9
      - y5^2
      - y9^2
      - x5
      - x9
      - x5^2
      - x9^2
      - X5
      - X9
      - X5^2
      - X9^2
      - z5
      - z9
      - z5^2
      - z9^2
      - Z5
      - Z9
      - Z5^2
      - Z9^2
    bgd_loc_path: # Path or leave empty to generate and save new permutation
    base_samp: 200
    extra_samp: [20, 500]
    bgd_sz: 100
    inputs_ignored: 3 # Trailing attributes to ignore for explanations in input vector
    dataset_queries:
      - "method == 'ETciD'"
    bgd_queries:
      - "peptide_length > 9"
  
  # Reconstituting a saved torch model
  model_settings:
    model_type: torch_prosit
    koina:
      model_path: Prosit_2024_intensity_PTMs_ac
      server_url: '10.162.163.66:9500'
      ssl: False
    local:
      model_path: "/cmnfs/proj/shabaz/model/2025-02-06_12-16-20/weights/model_epoch29_0.3015"
      ion_dict_path: "/cmnfs/proj/shabaz/model/2025-02-06_12-16-20/filtered_ion_dict.csv"
      token_dict_path: "/cmnfs/data/proteomics/shabaz_exotic/processed/merged_search/allinone/token_dictionary.txt"
      yaml_dir_path: "/cmnfs/proj/shabaz/model/2025-02-06_12-16-20/yaml"
  
shap_visualization:
  mode: b5+1
  sv_path: results/PrositAc/prosit_ac_realnfake/combined.parquet
  out_path: results/PrositAc/prosit_ac_realnfake/b5+1
  save_tokenframe: True
  filter_expr:
  bitoken: True
  position_combos:
    - [0,1]
    - [-1,0]
    - [0,4]
  clustering:
    run: False
    from_which_end: right
    number_of_aa: 6
