shap_calculator:
  # SHAP calculation settings
  shap_settings:
    val_data_path: "data/val_inps.parquet"
    output_dir: test
    mode:
      - b3+1
      - b5+1
      - b7+1
      - b9+1
      - y3+1
      - y5+1
      - y7+1
      - y9+1
      - b3+2
      - b5+2
      - b7+2
      - b9+2
      - y3+2
      - y5+2
      - y7+2
      - y9+2
    bgd_loc_path: # Path or leave empty to generate and save new permutation
    base_samp: 200
    extra_samp: [20, 500]
    bgd_sz: 100
    inputs_ignored: 3 # Trailing attributes to ignore for explanations in input vector
    dataset_queries:
      - "method == 'HCD'"
    bgd_queries:
      - "peptide_length > 9"
  
  # Reconstituting a saved torch model
  model_settings:
    model_type: koina
    koina:
      model_path: Prosit_2019_intensity
      server_url: 'koina.wilhelmlab.org:443'
      ssl: True
    local:
      model_path: "/cmnfs/proj/xai/2025-03-12_16-29-27/weights/model_epoch27_0.2910"
      ion_dict_path: "/cmnfs/proj/xai/2025-03-12_16-29-27/filtered_ion_dict.csv"
      token_dict_path: "/cmnfs/proj/xai/token_dictionary.txt"
      yaml_dir_path: "/cmnfs/proj/xai/2025-03-12_16-29-27/yaml"
  
shap_visualization:
  mode: b5+1
  sv_path: test/combined.parquet
  out_path: test/b5+1
  save_tokenframe: True
  filter_expr:
  bitoken: True
  position_combos:
    - [0,1]
    - [-1,0]
    - [0,4]
  clustering:
    run: False
    from_which_end: right
    number_of_aa: 6
