shap_calculator:
  # SHAP calculation settings
  shap_settings:
    val_data_path: "/cmnfs/proj/shap-prosit/data/denovo/bioplex.parquet" # read
    output_dir: bioplex # write
    bgd_loc_path: # read: Path or leave empty to generate and save new permutation
    base_samp: 100000 # setting
    bgd_sz: 100 # setting
    inputs_ignored: 2 # read/setting: Trailing attributes to ignore for explanations in input vector
    dataset_queries: # setting
      - "method == 'HCD'"
    bgd_queries: # setting
      - "peptide_length > 9"
  
  # Reconstituting a saved torch model
  model_settings:
    model_type: mdlm # setting
    koina:
      model_path: Prosit_2024_intensity_PTMs_ac # setting/read
      server_url: '10.162.163.66:9500' # setting
      ssl: False # setting
    local:
      model_path: "/cmnfs/proj/diffusion/experiments/2026-03-06_22-58-14" # read
      diffusion_steps: 0

