shap_calculator:
  # SHAP calculation settings
  shap_settings:
    val_data_path: "./data/9_species_V2_yeast_every_100.parquet" # read
    output_dir: test # write
    bgd_loc_path: # read: Path or leave empty to generate and save new permutation
    base_samp: 100000 # setting
    extra_samp: [20, 500] # setting
    bgd_sz: 100 # setting
    inputs_ignored: 2 # read/setting: Trailing attributes to ignore for explanations in input vector
    dataset_queries: # setting
      - "method == 'HCD'"
    bgd_queries: # setting
      - "peptide_length > 9"
  
  # Reconstituting a saved torch model
  model_settings:
    model_type: mdlm # setting
    koina:
      model_path: Prosit_2024_intensity_PTMs_ac # setting/read
      server_url: '10.162.163.66:9500' # setting
      ssl: False # setting
    local:
      model_path: "/cmnfs/proj/diffusion/experiments/2025-10-14_17-25-21" # read
      diffusion_steps: 2
  
shap_visualization:
  mode: y5 # setting
  sv_path: /cmnfs/proj/shabaz/shap/shabaz/EID/output.parquet # read
  out_path: test/y5 # write
  save_tokenframe: True # write
  filter_expr: # setting
  bitoken: False # setting
  position_combos: # setting
    - [0,1]
    - [-1,0]
    - [0,4]
  clustering: # setting
    run: False
    from_which_end: right
    number_of_aa: 6
